# Generated by Django 4.1.3 on 2022-11-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="user",
        ),
        migrations.AddField(
            model_name="log",
            name="device",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="main.device"
            ),
            preserve_default=False,
        ),
    ]
