# Generated by Django 4.1.3 on 2022-11-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_log_user_log_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="ldr_status",
            field=models.IntegerField(choices=[(1, "On"), (0, "Off")], default=0),
        ),
        migrations.AddField(
            model_name="device",
            name="ldr_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="motion_sensor_status",
            field=models.IntegerField(choices=[(1, "On"), (0, "Off")], default=0),
        ),
        migrations.AddField(
            model_name="device",
            name="motion_sensor_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="rain_sensor_status",
            field=models.IntegerField(choices=[(1, "On"), (0, "Off")], default=0),
        ),
        migrations.AddField(
            model_name="device",
            name="rain_sensor_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
