# Generated by Django 4.1.3 on 2022-11-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_device_ldr_status_device_ldr_threshold_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="description",
        ),
    ]
