# Generated by Django 4.1.3 on 2022-11-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_log_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="retraction_status",
            field=models.IntegerField(
                choices=[(0, "Retracted"), (1, "Extended")], default=0
            ),
        ),
    ]
